title:            Required for Jekyll
description:      A WordPress theme converted for Jekyll
disqus_shortname: required
#Comment out url when working locally to resolve base urls correctly
url:              http://japh.github.io/required-for-jekyll/

# Owner/author information
owner:
  name:           Japh
  avatar:         bio-photo.jpg
  email:          japh@satellitedev.com

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Tags
    url: /tags
  - title: Required on GitHub
    url: https://github.com/Japh/required-for-jekyll
    external: true
  - title: Twitter
    url: http://twitter.com/Japh
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Hobart
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]